version: 2

sources:
  - name: compass_raw
    schema: dbt_lkukunarapu
    database: neondb
    tables:
      - name: patients
        description: Raw patients table from Neon.
        columns:
          - name: patient_id
            description: Unique identifier for each patient.
          - name: site_id
            description: Site where patient is enrolled.
          - name: enroll_date
            description: Record creation timestamp.

      - name: sites
        description: Raw clinical site information.
        columns:
          - name: site_id
            description: Unique site identifier.
          - name: site_name
            description: Name of the clinical site.
          
      - name: assessments
        description: Raw patient assessment records.
        columns:
          - name: patient_id
            description: ID of patient who took the assessment.
          - name: day
            description: after how many days is follow-up
          - name: score
            description: Assessment score.
          - name: assessment_date
            description: When the assessment was conducted.
