version: 2

sources:
  - name: raw
    schema: public
    database: neondb
    tables:
      - name: patients
        description: Raw patients table from Neon.
        columns:
          - name: patient_id
            description: Unique identifier for each patient.
          - name: site_id
            description: Site where patient is enrolled.
          - name: created_at
            description: Record creation timestamp.

      - name: sites
        description: Raw clinical site information.
        columns:
          - name: site_id
            description: Unique site identifier.
          - name: site_name
            description: Name of the clinical site.
          - name: location
            description: Location of the site.

      - name: assessments
        description: Raw patient assessment records.
        columns:
          - name: assessment_id
            description: Unique identifier for each assessment.
          - name: patient_id
            description: ID of patient who took the assessment.
          - name: score
            description: Assessment score.
          - name: assessment_date
            description: When the assessment was conducted.
