version: 2

models:
  - name: stg_patients
    description: Cleaned and standardized patients data.
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique
      - name: site_id
        tests:
          - not_null
      - name: created_at

  - name: stg_sites
    description: Cleaned and standardized sites data.
    columns:
      - name: site_id
        tests:
          - not_null
          - unique
      - name: site_name
      - name: location

  - name: stg_assessments
    description: Cleaned assessments data.
    columns:
      - name: assessment_id
        tests:
          - not_null
          - unique
      - name: patient_id
        tests:
          - not_null
      - name: score
      - name: assessment_date
