version: 2

models:
  - name: stg_patients
    description: Cleaned patients data
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique
      - name: site_id
      - name: enroll_date
      - name: created_at

  - name: stg_sites
    description: Cleaned sites data
    columns:
      - name: site_id
        tests:
          - not_null
          - unique
      - name: site_name
      - name: location

  - name: stg_assessments
    description: Cleaned assessments data
    columns:
      - name: assessment_id
        tests:
          - not_null
          - unique
      - name: patient_id
      - name: severity_score
      - name: assessment_date
      - name: created_at
