version: 2

models:
  - name: stg_patients
    description: Cleaned patients data
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique
      - name: site_id
      - name: enroll_date
  

  - name: stg_sites
    description: Cleaned sites data
    columns:
      - name: site_id
        tests:
          - not_null
          - unique
      - name: site_name


  - name: stg_assessments
    description: Cleaned assessments data
    columns:
      - name: patient_id
      - name: day
      - name: severity_score
      - name: assessment_date
    
