name: 'compass_pathways_demo'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target"]

models:
  compass_pathways_demo:
    staging:
      materialized: view
    intermediate:
      materialized: table
    marts:
      materialized: table
